image:
  repository: ghcr.io/ainges/product-service
  tag: latest
replicaCount: 1

volume:
  enabled: true
  storageClassName: standard
  size: 2Gi
  mountPath: /app/data

service:
  port: 8080
  targetPort: 4000
  type: ClusterIP

# Ingress configuration
ingress:
  host: product-service.example.com

resources:
  requests:
    cpu: "250m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

# Liveness and Readiness Probes
livenessProbe:
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 5
  path: /health

readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 3
  path: /health