image:
  repository: ghcr.io/ainges/product-service
  tag: latest
replicaCount: 1
# Service configuration
service:
  port: 8080
  targetPort: 4000
  type: ClusterIP

# Ingress configuration
ingress:
  host: product-service.example.com

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
