{{- if .Values.postgres.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgres-payment-invoice-service
  labels:
    app: {{ .Release.Name }}-postgres-payment-invoice-service
spec:
  replicas: {{ .Values.postgres.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-postgres-payment-invoice-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-postgres-payment-invoice-service
    spec:
      containers:
      - name: postgres
        image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
        imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.postgres.service.targetPort }}
          livenessProbe:
            httpGet:
              path: {{ .Values.healthcheck.livenessProbePath }}
              port: {{ .Values.healthcheck.probePort }}
            initialDelaySeconds: {{ .Values.healthcheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthcheck.periodSeconds }}
            failureThreshold: {{ .Values.healthcheck.failureThreshold }}
            timeoutSeconds: {{ .Values.healthcheck.timeoutSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.healthcheck.readinessProbePath }}
              port: {{ .Values.healthcheck.probePort }}
            initialDelaySeconds: {{ .Values.healthcheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthcheck.periodSeconds }}
            failureThreshold: {{ .Values.healthcheck.failureThreshold }}
            timeoutSeconds: {{ .Values.healthcheck.timeoutSeconds }}
          startupProbe:
            httpGet:
              path: {{ .Values.healthcheck.startupProbePath }}
              port: {{ .Values.healthcheck.probePort }}
            initialDelaySeconds: {{ .Values.healthcheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthcheck.periodSeconds }}
            failureThreshold: {{ .Values.healthcheck.failureThreshold }}
            timeoutSeconds: {{ .Values.healthcheck.timeoutSeconds }}
        env:
        - name: POSTGRES_DB
          value: {{ .Values.postgres.env.POSTGRES_DB }}
        - name: POSTGRES_USER
          value: {{ .Values.postgres.env.POSTGRES_USER }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgres.env.POSTGRES_PASSWORD }}
        resources:
          limits:
            memory: {{ .Values.postgres.resources.limits.memory }}
            cpu: {{ .Values.postgres.resources.limits.cpu }}
          requests:
            memory: {{ .Values.postgres.resources.requests.memory }}
            cpu: {{ .Values.postgres.resources.requests.cpu }}
{{- end }}
