{{- if .Values.paymentInvoiceService.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-payment-invoice-service-ingress
  annotations:
{{ toYaml .Values.paymentInvoiceService.ingress.annotations | indent 4 }}
spec:
  rules:
    - host: {{ .Values.paymentInvoiceService.ingress.hostname }}
      http:
        paths:
          - path: {{ .Values.paymentInvoiceService.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-payment-invoice-service
                port:
                  number: {{ .Values.paymentInvoiceService.service.port }}
{{- end }}
