apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rabbitmq
spec:
  selector:
    app: {{ .Release.Name }}-rabbitmq
  ports:
    - name: amqp
      protocol: TCP
      port: {{ .Values.rabbitmq.service.ports.amqp.port }}
      targetPort: {{ .Values.rabbitmq.service.ports.amqp.targetPort }}
      nodePort: {{ .Values.rabbitmq.service.ports.amqp.nodePort }}
    - name: management
      protocol: TCP
      port: {{ .Values.rabbitmq.service.ports.management.port }}
      targetPort: {{ .Values.rabbitmq.service.ports.management.targetPort }}
      nodePort: {{ .Values.rabbitmq.service.ports.management.nodePort }}
  type: {{ .Values.rabbitmq.service.type }}
