apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-order-service
  labels:
    app: cart-order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-order-service
  template:
    metadata:
      labels:
        app: cart-order-service
    spec:
      containers:
        - name: cart-order-service
          image: ghcr.io/ainges/cart-order-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /q/health/live  # Liveness-Check
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /q/health/ready  # Readiness-Check
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /q/health/started  # Startup-Check
              port: 8080
            initialDelaySeconds: 10 # Wait 10 seconds before first check
            periodSeconds: 20
            failureThreshold: 5
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          env:
            - name: RABBITMQ_HOST
              value: "rabbitmq-service"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME
              value: "guest"
            - name: RABBITMQ_PASSWORD
              value: "guest"
            - name: RABBITMQ_HTTP_PORT
              value: "15672"
            - name: RABBITMQ_QUEUE_NAME_PENDING_ORDERS
              value: "pending-orders"
            - name: RABBITMQ_EXCHANGE_NAME
              value: ""
            - name: PROD_HOST
              value: "cart-order-service"
            - name: PROD_PORT
              value: "8080"
            - name: PRODUCT_SERVICE_URL
              value: "http://product-service:4000"
            - name: DB_KIND
              value: "postgresql"
            - name: DB_USERNAME
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
            - name: DB_JDBC_URL
              value: "jdbc:postgresql://postgres-cart-order-service:5432/cart_order_service"