apiVersion: v1
kind: Service
metadata:
  name: cart-order-service-service
spec:
  type: NodePort
  selector:
    app: cart-order-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080