apiVersion: v1
kind: Service
metadata:
  name: product-service-service
  labels:
    app: product-service-service
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 4000
