paymentInvoiceService:
  replicaCount: 1
  image:
    repository: ghcr.io/ainges/payment-invoice-service
    tag: latest
    pullPolicy: Always
  service:
    type: NodePort
    port: 8080
    targetPort: 8080
    nodePort: 30092
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    hostname: payment-invoice-service
    path: /
  resources:
    limits:
      memory: "512Mi"
      cpu: "500m"
    requests:
      memory: "256Mi"
      cpu: "250m"
      
healthcheck:
  livenessProbePath: "/q/health/live"
  readinessProbePath: "/q/health/ready"
  startupProbePath: "/q/health/started"
  wellProbePath: "/q/health/well"
  probePort: 80
  initialDelaySeconds: 5
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 2

  env:
    DefaultConnection: "Host=payment-invoice-service-postgres-payment-invoice-service;Port=5432;Database=payment_invoice_service;Username=postgres;Password=postgres"
    RabbitMq__Host: "rabbitmq-rabbitmq"
    RabbitMq__Username: "guest"
    RABBITMQ_PASSWORD: "guest"

# PostgreSQL Configuration
postgres:
  enabled: true
  replicaCount: 1
  image:
    repository: postgres
    tag: "14"
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 5432
    targetPort: 5432
    nodePort: 30093
  resources:
    limits:
      memory: "512Mi"
      cpu: "500m"
    requests:
      memory: "256Mi"
      cpu: "250m"
  env:
    POSTGRES_DB: payment_invoice_service
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
