image:
  repository: ghcr.io/ainges/user-service
  tag: latest
replicaCount: 1

volume:
  enabled: true
  storageClassName: standard
  size: 2Gi
  mountPath: /app/data

service:
  port: 8080
  targetPort: 5000
  type: ClusterIP

# Ingress configuration
ingress:
  host: user-service.example.com

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
    
livenessProbe:
  initialDelaySeconds: 10
readinessProbe:
  initialDelaySeconds: 5