name: Cart-Order-Service CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job 1: Build Docker Image
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install QEMU for cross-platform builds
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
          
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push multi-architecture Docker image
        working-directory: cart-order-service/
        run: |
          docker buildx create --use
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -f src/main/docker/Dockerfile.jvm-build \
            -t ghcr.io/ainges/cart-order-service:prerun \
            --push .
          
          
  # Job 2: Run Tests
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker.io
        uses: docker/login-action@v2
        with:
          username: cnd2024teamk # optional
          password: ${{ secrets.DOCKER_PAT }} 
          logout: false

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21' 

      - name: Set execute permission for mvnw
        working-directory: cart-order-service/
        run: chmod +x ./mvnw

      - name: Build the Maven artifact
        working-directory: cart-order-service/
        run: ./mvnw test 

  # Job 3: Push Docker Image to GHCR (only if both steps are successful)
  push:
    needs:
      - build
      - test
    runs-on: ubuntu-latest


    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Pre-Run Image
        run: docker pull ghcr.io/ainges/cnd-2024/cart-order-service:prerun

      - name: Re-Tag Pre-Run Image as Latest
        run: |
          docker tag ghcr.io/ainges/cnd-2024/cart-order-service:prerun ghcr.io/ainges/cnd-2024/cart-order-service:latest

      - name: Push Final Image
        run: docker push ghcr.io/ainges/cnd-2024/cart-order-service:latest
