name: Cart-Order-Service CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job 1: Build Docker Image
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install QEMU for cross-platform builds
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
          
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image as Tarball
        uses: docker/build-push-action@v6
        with:
          context: ./cart-order-service
          file: src/main/docker/Dockerfile.jvm-build
          platforms: linux/amd64,linux/arm64
          output: type=tar,dest=image.tar  # Speichert direkt als Tarball
          push: false
          tags: ghcr.io/ainges/cart-order-service:latest

      - name: Upload Docker Image Tarball
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: image.tar
          
          
  # Job 2: Run Tests
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker.io
        uses: docker/login-action@v2
        with:
          username: cnd2024teamk # optional
          password: ${{ secrets.DOCKER_PAT }} 
          logout: false

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21' 

      - name: Set execute permission for mvnw
        working-directory: cart-order-service/
        run: chmod +x ./mvnw

      - name: Build the Maven artifact
        working-directory: cart-order-service/
        run: ./mvnw test 

  # Job 3: Push Docker Image to GHCR (only if both steps are successful)
  push:
    needs:
      - build
      - test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Download Docker Image Tarball
        uses: actions/download-artifact@v3
        with:
          name: docker-image
          path: image.tar

      - name: Load Docker Image from Tarball
        run: docker load -i image.tar

      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/ainges/cart-order-service:latest
