name: Cart-Order-Service CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job 1: Build Docker Image
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install QEMU for cross-platform builds
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
          
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        if: steps.changes.outputs.any_modified == 'true'
        uses: docker/build-push-action@v6
        with:
          context: backend/${{ matrix.service }}/
          file: cart-order-service/src/main/docker/Dockerfile.jvm-build
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ghcr.io/${{ github.repository_owner }}/cart-order-service:latest
          
  # Job 2: Run Tests
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

        # Log in to Docker Hub to ensure access rate-limited images
        # Some test containers may rely on images from Docker Hub. Without authentication, pulling these images
        # might fail due to rate limits...
      - name: Login to Docker.io
        uses: docker/login-action@v3.3.0
        with:
          username: cnd2024teamk # optional
          password: ${{secrets.DOCKER_PAT}} 
          logout: false

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21' 

      - name: Set execute permission for mvnw
        working-directory: cart-order-service/
        run: chmod +x ./mvnw

      - name: Build the Maven artifact
        working-directory: cart-order-service/
        run: ./mvnw test 

  # Job 3: Push Docker Image to GHCR (only if both steps are successful)
  push:
    needs:
      - build
      - test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/my-quarkus-app:latest
