name: payment-invoice-service-ci.yml

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./payment-invoice-service/payment-invoice-service

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  build:
      needs:
        - test
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
  
        - name: Install QEMU for cross-platform builds
          uses: docker/setup-qemu-action@v3
  
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3.8.0
            
        - name: Log in to GitHub Container Registry
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
  
        - name: Build and push multi-architecture Docker image
          working-directory: payment-invoice-service/payment-invoice-service
          run: |
            docker buildx create --use
            docker buildx build \
              --platform linux/amd64,linux/arm64 \
              -f Dockerfile \
              -t ghcr.io/ainges/payment-invoice-service:latest \
              --push .
