name: payment-invoice-service-ci.yml

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  cancel-previous:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1

  test:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./payment-invoice-service/payment-invoice-service-tests
  
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal

  build:
      needs:
        - test
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
  
        - name: Install QEMU for cross-platform builds
          uses: docker/setup-qemu-action@v3
  
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3.8.0
            
        - name: Log in to GitHub Container Registry
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}     
            
            
          
        - name: Build and push multi-architecture Docker image
          uses: nick-fields/retry@v3
          with:
            timeout_seconds: 600
            max_attempts: 20
            retry_on: error
            command: |
                bash -c "docker buildx create --use && \
                        docker buildx build \
                          --platform linux/amd64,linux/arm64 \
                          -f payment-invoice-service/payment-invoice-service/Dockerfile \
                          -t ghcr.io/ainges/payment-invoice-service:dev \
                          --push ./payment-invoice-service/payment-invoice-service"
