name: Product-Service CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job 1: Run Tests
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: |
          cd product-service
          npm install

      - name: Run tests
        run: |
          cd product-service
          npm test

  # Job 2: Build Docker Image (Pre-Run)
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push pre-run Docker image
        working-directory: product-service/
        run: |
          docker build -t ghcr.io/ainges/product-service:prerun -f Dockerfile .
          docker push ghcr.io/ainges/product-service:prerun

  # Job 3: Push Final Image (after build and tests)
  push:
    name: Push Final Docker Image
    needs:
      - test
      - build
    runs-on: ubuntu-latest

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Pre-Run Image
        run: docker pull ghcr.io/ainges/product-service:prerun

      - name: Re-Tag Pre-Run Image as Latest
        run: |
          docker tag ghcr.io/ainges/product-service:prerun ghcr.io/ainges/product-service:latest

      - name: Push Final Image
        run: docker push ghcr.io/ainges/product-service:latest
