name: User-Service CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job 1: Run Tests
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r user-service/requirements.txt

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest user-service/tests --maxfail=5 --disable-warnings

  # Job 2: Build Docker Image (Pre-Run)
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push pre-run Docker image
        working-directory: user-service/
        run: |
          docker build -t ghcr.io/ainges/user-service:prerun -f Dockerfile .
          docker push ghcr.io/ainges/user-service:prerun

  # Job 3: Push Final Image (after build and tests)
  push:
    name: Push Final Docker Image
    needs:
      - test
      - build
    runs-on: ubuntu-latest

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Pre-Run Image
        run: docker pull ghcr.io/ainges/user-service:prerun

      - name: Re-Tag Pre-Run Image as Latest
        run: |
          docker tag ghcr.io/ainges/user-service:prerun ghcr.io/ainges/user-service:latest

      - name: Push Final Image
        run: docker push ghcr.io/ainges/user-service:latest
